const name = 'better-datepicker'
export const wrapper = `${name}-wrapper`
export const header = `${name}-header`
export const day = `${name}-day`
export const dayBar = `${day}-bar`
export const dayContent = `${day}-content`
export const month = `${name}-month`
export const year = `${name}-year`
export const show = `${name}-show`
export const hidden = `${name}-hidden`
export const float = `${name}-float `
export const defaultCursor = `${name}-default-cursor `
export const today = `${name}-today`
